include: package:lint/analysis_options.yaml

analyzer:
  exclude:
    - lib/*/*.g.dart
    - lib/*/*.freezed.dart
  strong-mode:
    implicit-dynamic: false

linter:
  rules:
    sort_constructors_first: true
    prefer_single_quotes: true
